on:
  push:
    branches: [main]


name: zoominfo appp Project CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: docker/login-action@v2
        with:
          registry: 820774903764.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 820774903764.dkr.ecr.eu-west-1.amazonaws.com
          ECR_REPOSITORY: zoominfo-service2
          IMAGE_TAG: 1.0
        run: |
          # Build a docker container and push it to ECR 
          #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t zoominfo-service2 .
          docker tag zoominfo-service2:latest 820774903764.dkr.ecr.eu-west-1.amazonaws.com/zoominfo-service2:latest
          echo "Pushing image to ECR..."
          docker push 820774903764.dkr.ecr.eu-west-1.amazonaws.com/zoominfo-service2:latest
          #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          #echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
